DemoProject/Controllers/CandidateRegistrationController.cs
using DemoProject.Models;
using DemoProject.Models.ViewModels;
using DemoProject.Services.Abstraction;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace DemoProject.Controllers
{
    public class CandidateRegistrationController : Controller
    {
        private readonly IRegistrationService _registrationService;

        public CandidateRegistrationController(IRegistrationService registrationService)
        {
            _registrationService = registrationService;
        }

        [HttpGet]
        public IActionResult Index(string schoolCode)
        {
            // Get school based on provided school code
            School school = _registrationService.GetSchoolByCode(schoolCode);

            if (school == null)
            {
                return RedirectToAction("SchoolCodeNotFound");
            }

            // Pass the school ID to the view
            return View(school);
        }

        [HttpPost]
        public IActionResult RegisterCandidate(RegistrationViewModel candidateViewModel)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the school based on the entered school code
                School school = _registrationService.GetSchoolByCode(candidateViewModel.SchoolCode);

                if (school == null)
                {
                    ModelState.AddModelError("SchoolCode", "School with the provided code does not exist.");
                    return View("Index", candidateViewModel);
                }

                // Now you have the school ID, use it to associate the candidate
                CompletedViewModel registeredCandidate = _registrationService.RegisterCandidate(candidateViewModel, school.SchoolId);

                // Convert the passport image to Base64 and assign it to the view model
                if (candidateViewModel.Passport != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        candidateViewModel.Passport.CopyTo(memoryStream);
                        var bytes = memoryStream.ToArray();
                        var base64 = Convert.ToBase64String(bytes);
                        registeredCandidate.PassportBase64 = base64;
                    }
                }
                registeredCandidate.SchoolCode = school.SchoolCode;

                return View("Confirmation", registeredCandidate);
            }

            return View("Index");
        }

        [HttpGet]
        public IActionResult SchoolCodeNotFound()
        {
            return View();
        }
    }
}

DemoProject/Views/CandidateRegistration/Confirmation.cshtml
@model DemoProject.Models.ViewModels.CompletedViewModel

@{
    ViewData["Title"] = "Confirmation";
}
<body class="body bg-primary">
    <div class="text-center">
        <a href="@Url.Action("Index", "Home")" class="btn btn-link" style="font-weight: 700; color: #FFFFFF;">Gameplay</a>
    </div>

    @if (!string.IsNullOrEmpty(Model.PassportBase64))
    {
        <div class="container">
            <img src="data:image/jpeg;base64,@Model.PassportBase64" alt="Passport">
        </div>
    }

    <div class="container">
        <p><strong>@Model.FullName</strong></p>
        <p><strong>@Model.ID</strong></p>
        <p><strong>@Model.Category</strong></p>
    </div>
    </div>
    <div class="text-center mt-4">
        <a href="javascript:void(0);" onclick="navigateToNewRegistration('@Model.SchoolCode')" class="link-new-registration">New Registration</a>
    </div>

    @section Scripts {
        <script>
            // Function to navigate to the new registration page
            function navigateToNewRegistration(schoolCode) {
                console.log("Clicked on 'New Registration'");
             //log the schoolcode
                console.log("School Code:", schoolCode);
                // Construct the URL with the schoolCode parameter
                var url = "@Url.Action("Index", "CandidateRegistration")?schoolCode=" + schoolCode;
                // Redirect to the new registration page
                window.location.href = url;
            }
        </script>
    }
</body>

DemoProject/Views/CandidateRegistration/Index.cshtml
@model School
@{
    ViewData["Title"] = "Candidate Registration";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
<body class="body bg-primary">
    <div class="text-center">
        <a href="@Url.Action("Index", "Home")" class="btn btn-link" style="font-weight: 700; color: #FFFFFF;">Gameplay</a>
    </div>

    <div class="container">
        <h1>Fill in your details to register</h1>
        <form id="registrationForm" method="post" action="CandidateRegistration/RegisterCandidate" class="registration-form" enctype="multipart/form-data">
            <input type="text" class="form-control" id="SchoolCode" name="SchoolCode" value="@Model.SchoolCode" hidden required />
            <input type="text" class="form-control" id="SchoolId" name="SchoolId" value="@Model.SchoolId" hidden required />
            <input type="text" class="form-control" id="SchoolName" name="SchoolName" value="@Model.Name" hidden required />
            <div class="form-group">
                <label for="FirstName" class="form-label">First Name:</label>
                <input type="text" class="form-control" id="FirstName" name="FirstName" required />
            </div>

            <div class="form-group">
                <label for="MiddleName" class="form-label">Middle Name:</label>
                <input type="text" class="form-control" id="MiddleName" name="MiddleName" />
            </div>

            <div class="form-group">
                <label for="LastName" class="form-label">Last Name:</label>
                <input type="text" class="form-control" id="Surname" name="Surname" required />
            </div>

            <div class="form-group">
                <label class="form-label">Gender:</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Gender" id="MaleGender" value="Male" required />
                    <label class="form-check-label" for="MaleGender">Male</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Gender" id="FemaleGender" value="Female" required />
                    <label class="form-check-label" for="FemaleGender">Female</label>
                </div>
            </div>

            <div class="form-group">
                <label for="DOB" class="form-label">Date of Birth:</label>
                <input type="date" class="form-control" id="DateOfBirth" name="DateOfBirth" required />
            </div>

            <div class="form-group">
                <label for="Email" class="form-label">Email:</label>
                <input type="email" class="form-control" id="Email" name="Email" required />
                <span id="emailError" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="form-label">Category:</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Category" id="Junior" value="Junior" required />
                    <label class="form-check-label" for="Junior">Junior</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Category" id="Senior" value="Senior" required />
                    <label class="form-check-label" for="Senior">Senior</label>
                </div>
            </div>

            <div class="form-group">
                <label for="Passport" class="form-label"> Passport Photo:</label>
                <input type="file" class="form-control-file" id="Passport" name="Passport" accept=".jpg, .jpeg, .png" required />
            </div>
            <button type="button" id="nextButton" class="btn btn-primary">Next</button>
        </form>
    </div>

    <script>
        document.getElementById("Email").addEventListener("blur", function () {
            var email = this.value;
            var emailPattern = /^[a-zA-Z0-9._-]+@@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
            var errorMessage = document.getElementById("emailError");

            if (!emailPattern.test(email)) {
                errorMessage.textContent = "Please enter a valid email address.";
                this.classList.add("is-invalid");
            } else {
                errorMessage.textContent = ""; // Clear the error message
                this.classList.remove("is-invalid");
            }
        });

        document.getElementById("nextButton").addEventListener("click", function() {
            // Check if there are any validation errors
            var emailInput = document.getElementById("Email");
            var errorMessage = document.getElementById("emailError");

            if (emailInput.classList.contains("is-invalid")) {
                alert("Please fix validation errors before proceeding.");
                emailInput.focus();
            } else {
                // Submit the form if it's valid
                var form = document.getElementById("registrationForm");
                form.submit();
            }
        });

        // Add event listener to capture "Enter" key press
        document.getElementById("Email").addEventListener("keydown", function (event) {
            if (event.key === "Enter") {
                document.getElementById("nextButton").click();
            }
        });
    </script>
</body>
</html>